### ISSUE TITLE
Custom tag format?

### ISSUE THREAD

**Issue by baptisteArno** [jaywcjlove/create-tag-action#246]
Is it possible to generate a custom tag format like: `react/v1.1.0`?

**Comment by gcrozariol** [comment]
Is it possible to remove the "v" before the version number, so the tag is i.e. **1.0.0**, instead of **v1.0.0**?

**Comment by jaywcjlove** [comment]
I tested it and it totally works. @gcrozariol 

```yml
- name: Create Tag
  uses: jaywcjlove/create-tag-action@main
  with:
    version: '1.2.3'
```
