### ISSUE TITLE
Input Version not handled if invalid version number in existing tags

### ISSUE THREAD

**Issue by tobitege** [jaywcjlove/create-tag-action#288]
If a repository (unfortunately) has non-Semver conformant tag version numbers, the action will fail with e.g.
    ERROR: Invalid version: 0.640
As far as I understand the code, it seems to stop processing in the main.ts file _before_ reaching line 55 to actually process a specified input version number like 0.7.0.0

IF a version is explicitly specified in the action, shouldn't this preceed any iteration of the "listTags" object?

**Comment by jaywcjlove** [comment]
https://github.com/jaywcjlove/create-tag-action/blob/b2db07a868ae5bff1e91c678a1b1bda33d426288/src/main.ts#L55

Is adding a version number a correct judgment?
@tobitege

**Comment by tobitege** [comment]
> Is adding a version number a correct judgment? @tobitege

The code line 55 you quoted is the one I was refering to, yes.
The action does not seem to get to that point as it errors with an exception first.

**Comment by tobitege** [comment]
You're fixing something I didn't mean. The problem is that the action aborts with an exception when processing the list of existing tags in a repository - with or without a version used as input.

**Comment by jaywcjlove** [comment]
@tobitege Invalid label in existing label list?

**Comment by tobitege** [comment]
Repository has a Release tagged 0.640 and this causes an "Invalid number" exception.
This happens **before** the input version is checked.

**Comment by jaywcjlove** [comment]
@tobitege Upgrade `v1.3.11`

**Comment by tobitege** [comment]
Thank you! I will try it again and let you know! :)

**Comment by tobitege** [comment]
@jaywcjlove I tried again with this action configuration:
```
        - name: Create Tag
          if: github.ref == 'refs/heads/master'  # ONLY ON MASTER
          id: create_tag
          uses: jaywcjlove/create-tag-action@main
          with:
            release: true
            test: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'
```
In the workflow log for the Create Tag action it shows:
```
Warning: Invalid version number "v0.640".
Commit Content: Release v0.7.1
This is not a tagged push.
```
So the invalid version number on already existing tag is now a warning and not an exception, which is good. :)
(weird is, github seems to give you the list of existing tags not in chronological order as the 0.640 is not the most recent tag and not the tag of the latest release, but that is a different issue).

I'm not sure why my commit content is not correct for the pattern? Shouldn't it detect 0.7.1 as version?
