### ISSUE TITLE
Error: Not found

### ISSUE THREAD

**Issue by d0ctr** [jaywcjlove/create-tag-action#325]
Hi, I have tried using your action in the following configuration:
```yaml
name: 'Autotag'

on: 
  push:
    branches: 
      - main
    paths-ignore:
      - '.github/**/*.yml'
      - '.gitignore'

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Tag
        id: create_tag
        uses: jaywcjlove/create-tag-action@main
        with:
          package-path: ./package.json
```
And for some reason, all I get is ```Error: Not found``` while your action is being run.
Maybe I am just blind and stupid, but I can't get what I am doing wrong.
FYI: I have another action in a separate file that bumps the version in package.json file in new PRs.
