### ISSUE TITLE
[BUG] steps.create_tag.outputs.successful 在未创建标签时为空，而不是false

### ISSUE THREAD

**Issue by bling-yshs** [jaywcjlove/create-tag-action#336]
这是我的workflow，例子在 https://github.com/bling-yshs/action-test/actions/runs/9249133856/job/25440491477
```yaml
name: test
on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Tag
        id: create_tag
        uses: jaywcjlove/create-tag-action@main
        with:
          test: '^release:'

      - run: echo ${{ steps.create_tag.outputs.successful }}

      - run: echo "yes"
        if: steps.create_tag.outputs.successful == 'true'

      - run: echo "no"
        if: steps.create_tag.outputs.successful == 'false'
```
